[workspace]
members = ["programs/*", "clients/rust/*", "tools/*"]
exclude = ["observability/indexer"]

[workspace.dependencies]
solana-client = "=1.14.11"
solana-sdk = "=1.14.13"
solana-logger = "=1.14.13"
solana-program = "=1.14.13"
solana-program-test = "=1.14.13"
solana-account-decoder = "=1.14.12"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
