[package]
name = "test-utilities"
version = "0.1.0"
publish = false
edition = "2021"

[features]
lip = ["liquidity-incentive-program"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.26.0"
anchor-lang-27 = { version = "0.27.0", package = "anchor-lang" }
anchor-spl = "0.26.0"
bytemuck = "1.9.1"
fixed = "1.12.0"
fixed-macro = "1.2.0"
lazy_static = "1.4.0"
pyth-sdk-solana = "0.7.0"
static_assertions = "1.1.0"
type-layout = "0.2.0"
anyhow = "1.0.66"
assert_matches = "1.5.0"
bincode = "1.3.3"
futures = "0.3.25"
pretty_assertions = "1.2.1"
solana-program = "1.14.13"
solana-logger = "1.14.13"
solana-program-test = "1.14.13"
solana-sdk = "1.14.13"
switchboard-v2 = "0.1.22"

[dependencies.marginfi]
path = "../programs/marginfi"

[dependencies.liquidity-incentive-program]
path = "../programs/liquidity-incentive-program"
optional = true
